global:
  scrape_interval: 10s
  external_labels:
    monitor: 'monitoring'

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'localhost:9050' ]

  - job_name: 'nodeexporter'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'localhost:9060' ]

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: [ 'localhost:9061' ]
