{
 "title": "Host v2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "origin_prometheus",
    "label": "Origin_prom",
    "query": {
     "query": "label_values(origin_prometheus)"
    }
   },
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\"}, job)"
    }
   },
   {
    "name": "hostname",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}, nodename)"
    }
   },
   { "name": "node", "label": "Instance", "query": "prometheus" },
   {
    "name": "device",
    "label": "NIC",
    "query": {
     "query": "label_values(node_network_info{origin_prometheus=~\"$origin_prometheus\",device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   { "name": "maxmount", "label": "maxmount", "query": { "query": "" } },
   {
    "name": "show_hostname",
    "label": "show_hostname",
    "query": {
     "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}, nodename)"
    }
   },
   {
    "name": "total",
    "label": "total_servers",
    "query": {
     "query": "query_result(count(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resource Overview (associated JOB)，Host：$show_hostname，Instance：$node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds)"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU%",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$interval])) * 100)"
    }
   ]
  },
  {
   "title": "RAM%",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))* 100"
    }
   ]
  },
  {
   "title": "Disk Used%",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n\tnode_filesystem_size_bytes{mountpoint=\"/\", device!=\"/dev/mapper/cl_nexus-root\", fstype!=\"rootfs\", device!=\"/dev/bitbucket-prod-vg/root\"} - node_filesystem_free_bytes{mountpoint=\"/\", device!=\"/dev/mapper/cl_nexus-root\",fstype!=\"rootfs\", device!=\"/dev/bitbucket-prod-vg/root\"} \n\tor \n\tnode_filesystem_size_bytes{mountpoint=\"/usr/local/nexus-data\"} - node_filesystem_free_bytes{mountpoint=\"/usr/local/nexus-data\"}\n\tor \n\tnode_filesystem_size_bytes{mountpoint=\"/opt\"} - node_filesystem_free_bytes{mountpoint=\"/opt\"}\n) /\n\t\n(\n\t(node_filesystem_size_bytes{mountpoint=\"/\", device!=\"/dev/mapper/cl_nexus-root\", fstype!=\"rootfs\", device!=\"/dev/bitbucket-prod-vg/root\"} - node_filesystem_free_bytes{mountpoint=\"/\", device!=\"/dev/mapper/cl_nexus-root\",fstype!=\"rootfs\", device!=\"/dev/bitbucket-prod-vg/root\"} \n\tor \n\tnode_filesystem_size_bytes{mountpoint=\"/usr/local/nexus-data\"} - node_filesystem_free_bytes{mountpoint=\"/usr/local/nexus-data\"}\n\tor \n\tnode_filesystem_size_bytes{mountpoint=\"/opt\"} - node_filesystem_free_bytes{mountpoint=\"/opt\"}\n\t)\n\t+ \n\t(node_filesystem_avail_bytes {mountpoint=\"/\", device!=\"/dev/mapper/cl_nexus-root\",fstype!=\"rootfs\", device!=\"/dev/bitbucket-prod-vg/root\"}\n\tor \n\tnode_filesystem_avail_bytes {mountpoint=\"/usr/local/nexus-data\"}\n\tor\n\tnode_filesystem_avail_bytes {mountpoint=\"/opt\"})\n) * 100"
    }
   ]
  },
  {
   "title": "Disk Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\", device!=\"/dev/mapper/cl_nexus-root\",fstype!=\"rootfs\", device!=\"/dev/bitbucket-prod-vg/root\"} \nor \nnode_filesystem_size_bytes{mountpoint=\"/usr/local/nexus-data\"} \nor \nnode_filesystem_size_bytes{mountpoint=\"/opt\"}"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\", device!=\"/dev/mapper/cl_nexus-root\", fstype!=\"rootfs\", device!=\"/dev/bitbucket-prod-vg/root\"} - node_filesystem_free_bytes{mountpoint=\"/\", device!=\"/dev/mapper/cl_nexus-root\",fstype!=\"rootfs\", device!=\"/dev/bitbucket-prod-vg/root\"} \nor \nnode_filesystem_size_bytes{mountpoint=\"/usr/local/nexus-data\"} - node_filesystem_free_bytes{mountpoint=\"/usr/local/nexus-data\"}\nor \nnode_filesystem_size_bytes{mountpoint=\"/opt\"} - node_filesystem_free_bytes{mountpoint=\"/opt\"}"
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes {mountpoint=\"/\", device!=\"/dev/mapper/cl_nexus-root\",fstype!=\"rootfs\", device!=\"/dev/bitbucket-prod-vg/root\"}\nor \nnode_filesystem_avail_bytes {mountpoint=\"/usr/local/nexus-data\"}\nor\nnode_filesystem_avail_bytes {mountpoint=\"/opt\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode='system'})"
    }
   ]
  },
  {
   "title": "Total Swap",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_SwapTotal_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Resource Details：【$show_hostname】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }
  },
  {
   "title": "【$show_hostname】：Disk Space Used Basic(EXT?/XFS)",
   "type": "table-old",
   "description": "In this kanban: the total disk, usage, available, and usage rate are consistent with the values of the Size, Used, Avail, and Use% columns of the df command, and the value of Use% will be rounded to one decimal place, which will be more accurate .\n\nNote: The Use% algorithm in df is: (size-free) * 100 / (avail + (size-free)), the result is divisible by this value, non-divisible by this value is +1, and the unit of the result is %.\nRefer to the df command source code:",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "总量"
    },
    {
     "expr": "node_filesystem_avail_bytes {fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0"
    },
    {
     "expr": "(node_filesystem_size_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))"
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(rate(node_disk_read_bytes_total{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}[$interval])) by (instance)",
     "legendFormat": "{{device}}_Read bytes"
    }
   ]
  },
  {
   "title": "Download",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(rate(node_network_receive_bytes_total{device=~\"$device\"}[$interval])*8)",
     "legendFormat": "{{device}}_Read bytes"
    }
   ]
  },
  {
   "title": " Rx 30d",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(increase(node_network_receive_bytes_total{device=~\"$device\"}[30d]))",
     "legendFormat": "{{device}}_Read bytes"
    }
   ]
  },
  {
   "title": "Internet traffic in 30m $device",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 6 },
   "yaxes": [
    { "format": "bytes", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{device=~\"$device\"}[30m])",
     "legendFormat": "{{device}}_receive"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{device=~\"$device\"}[30m])",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(rate(node_disk_written_bytes_total[$interval]))",
     "legendFormat": "{{device}}_Read bytes"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(rate(node_network_transmit_bytes_total{device=~\"$device\"}[$interval])*8)",
     "legendFormat": "{{device}}_Read bytes"
    }
   ]
  },
  {
   "title": "Tx 30d",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(increase(node_network_transmit_bytes_total{device=~\"$device\"}[30d]))",
     "legendFormat": "{{device}}_Read bytes"
    }
   ]
  },
  {
   "title": "CPU% Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"system\"}[$interval])) by (instance) *100",
     "legendFormat": "System"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"user\"}[$interval])) by (instance) *100",
     "legendFormat": "User"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"iowait\"}[$interval])) by (instance) *100",
     "legendFormat": "Iowait"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$interval])) by (instance))*100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Total" },
    {
     "expr": "node_memory_MemTotal_bytes- node_memory_MemAvailable_bytes",
     "legendFormat": "Used"
    },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "Avaliable" },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "Used%"
    },
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes+ 1)/ (node_memory_SwapTotal_bytes + 1))) * 100",
     "legendFormat": "Swap%"
    }
   ]
  },
  {
   "title": "Network bandwidth usage per second $device",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "bps", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"$device\"}[$interval])*8",
     "legendFormat": "{{device}}_receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"$device\"}[$interval])*8",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "1m" },
    { "expr": "node_load5", "legendFormat": "5m" },
    { "expr": "node_load15", "legendFormat": "15m" },
    {
     "expr": " sum(count(node_cpu_seconds_total{mode='system'}) by (cpu,instance)) by(instance)",
     "legendFormat": "CPU cores"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "graph",
   "description": "Per second read / write bytes ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[$interval])",
     "legendFormat": "{{device}}_Read bytes"
    },
    {
     "expr": "rate(node_disk_written_bytes_total[$interval])",
     "legendFormat": "{{device}}_Written bytes"
    }
   ]
  },
  {
   "title": "Disk Space Used% Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}