{
 "title": "Host",
 "description": "Jobs queue speeds and rates, Executors availability, Nodes status, Jenkins and JVM resource usage.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"system\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "CPUs usage that is not idle",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100-sum(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\"}))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/\", device!=\"/dev/mapper/cl_nexus-root\",fstype!=\"rootfs\", device!=\"/dev/bitbucket-prod-vg/root\"} - node_filesystem_avail_bytes {mountpoint=\"/\", device!=\"/dev/mapper/cl_nexus-root\",fstype!=\"rootfs\", device!=\"/dev/bitbucket-prod-vg/root\"}) / node_filesystem_size_bytes{mountpoint=\"/\", device!=\"/dev/mapper/cl_nexus-root\",fstype!=\"rootfs\", device!=\"/dev/bitbucket-prod-vg/root\"}  * 100 \nor \n(node_filesystem_size_bytes{mountpoint=\"/usr/local/nexus-data\"} - node_filesystem_avail_bytes {mountpoint=\"/usr/local/nexus-data\"}) / node_filesystem_size_bytes{mountpoint=\"/usr/local/nexus-data\"}  * 100 \nor \n(node_filesystem_size_bytes{mountpoint=\"/opt\"} - node_filesystem_avail_bytes {mountpoint=\"/opt\"}) / node_filesystem_size_bytes{mountpoint=\"/opt\"}  * 100"
    }
   ]
  },
  {
   "title": "Total Storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\", device!=\"/dev/mapper/cl_nexus-root\",fstype!=\"rootfs\", device!=\"/dev/bitbucket-prod-vg/root\"} \nor \nnode_filesystem_size_bytes{mountpoint=\"/usr/local/nexus-data\"} \nor \nnode_filesystem_size_bytes{mountpoint=\"/opt\"}"
    }
   ]
  },
  {
   "title": "Storage Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\", device!=\"/dev/mapper/cl_nexus-root\", fstype!=\"rootfs\", device!=\"/dev/bitbucket-prod-vg/root\"} - node_filesystem_free_bytes{mountpoint=\"/\", device!=\"/dev/mapper/cl_nexus-root\",fstype!=\"rootfs\", device!=\"/dev/bitbucket-prod-vg/root\"} \nor \nnode_filesystem_size_bytes{mountpoint=\"/usr/local/nexus-data\"} - node_filesystem_free_bytes{mountpoint=\"/usr/local/nexus-data\"}\nor \nnode_filesystem_size_bytes{mountpoint=\"/opt\"} - node_filesystem_free_bytes{mountpoint=\"/opt\"}"
    }
   ]
  },
  {
   "title": "Storage Free",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes {mountpoint=\"/\", device!=\"/dev/mapper/cl_nexus-root\",fstype!=\"rootfs\", device!=\"/dev/bitbucket-prod-vg/root\"}\nor \nnode_filesystem_avail_bytes {mountpoint=\"/usr/local/nexus-data\"}\nor\nnode_filesystem_avail_bytes {mountpoint=\"/opt\"}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes/1024/1024/1000"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total[1m])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\"}))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "load 1m" }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_procs_running", "legendFormat": "running" },
    { "expr": "node_procs_blocked", "legendFormat": "blocked by I/O" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)",
     "legendFormat": "Used"
    },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Free" },
    { "expr": "node_memory_Buffers_bytes", "legendFormat": "Buffers" },
    { "expr": "node_memory_Cached_bytes", "legendFormat": "Cached" }
   ]
  },
  {
   "title": "Interrupts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": " irate(node_intr_total[5m])", "legendFormat": "interrupts" }
   ]
  },
  {
   "title": "I/O Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total[1m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total[1m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total[1m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device!=\"lo\"}[1m])"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{device!=\"lo\"}[1m])"
    }
   ]
  }
 ]
}